import os
import qrcode
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image as RLImage
from io import BytesIO
from app.config import settings

def generate_risk_card(analysis_id: str, data: dict) -> str:
    """Generate a PDF risk card and return the file path."""
    output_dir = os.path.join(settings.UPLOAD_DIR, "risk_cards")
    os.makedirs(output_dir, exist_ok=True)
    file_path = os.path.join(output_dir, f"risk_card_{analysis_id}.pdf")
    
    doc = SimpleDocTemplate(file_path, pagesize=A4)
    styles = getSampleStyleSheet()
    elements = []
    
    # Header
    title_style = ParagraphStyle(
        'TitleStyle', parent=styles['Heading1'], 
        textColor=colors.HexColor("#1D9E75"), fontSize=24, spaceAfter=10
    )
    elements.append(Paragraph("NaijaLex", title_style))
    elements.append(Paragraph("Legal Document Analysis Card", styles['Heading3']))
    elements.append(Spacer(1, 12))
    
    # Document Info
    doc_info = [
        [Paragraph(f"<b>Type:</b> {data['document_type']}", styles['Normal']), 
         Paragraph(f"<b>Date:</b> {data['date']}", styles['Normal'])]
    ]
    t_info = Table(doc_info, colWidths=[250, 250])
    elements.append(t_info)
    elements.append(Spacer(1, 12))
    
    # Risk Level Badge
    risk_colors = {
        "High": colors.HexColor("#E24B4A"),
        "Medium": colors.HexColor("#BA7517"),
        "Low": colors.HexColor("#1D9E75")
    }
    risk_color = risk_colors.get(data['overall_risk'], colors.grey)
    
    risk_style = ParagraphStyle(
        'RiskStyle', parent=styles['Normal'],
        textColor=colors.white, alignment=1, fontSize=16,
        backColor=risk_color, borderPadding=10
    )
    elements.append(Paragraph(f"OVERALL RISK: {data['overall_risk'].upper()}", risk_style))
    elements.append(Spacer(1, 20))
    
    # Clause Table
    table_data = [["Clause Title", "Severity", "Recommended Action"]]
    for clause in data['clauses'][:5]:
        table_data.append([
            Paragraph(clause['title'], styles['Normal']),
            clause['severity'],
            Paragraph(clause['action'], styles['Normal'])
        ])
    
    t_clauses = Table(table_data, colWidths=[150, 100, 250])
    t_clauses.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor("#1D9E75")),
        ('TEXTCOLOR', (0,0), (-1,0), colors.white),
        ('GRID', (0,0), (-1,-1), 0.5, colors.grey),
        ('VALIGN', (0,0), (-1,-1), 'TOP'),
    ]))
    elements.append(t_clauses)
    elements.append(Spacer(1, 20))
    
    # Top 3 Actions
    elements.append(Paragraph("<b>Top 3 Recommended Actions:</b>", styles['Heading3']))
    for i, action in enumerate(data['top_3_actions'], 1):
        elements.append(Paragraph(f"{i}. {action}", styles['Normal']))
    elements.append(Spacer(1, 20))
    
    # QR Code
    qr_url = f"{settings.APP_BASE_URL}/analysis/{analysis_id}"
    qr = qrcode.QRCode(version=1, box_size=10, border=5)
    qr.add_data(qr_url)
    qr.make(fit=True)
    qr_img = qr.make_image(fill_color="black", back_color="white")
    
    img_buffer = BytesIO()
    qr_img.save(img_buffer, format='PNG')
    img_buffer.seek(0)
    
    elements.append(RLImage(img_buffer, width=100, height=100))
    elements.append(Paragraph("Scan to view full analysis & negotiation drafts", styles['Small']))
    
    # Footer
    elements.append(Spacer(1, 50))
    footer_style = ParagraphStyle('Footer', parent=styles['Italic'], fontSize=8, alignment=1)
    elements.append(Paragraph("Generated by NaijaLex — Not legal advice. Consult a qualified lawyer for complex matters.", footer_style))
    
    doc.build(elements)
    return file_path
